### ISSUE TITLE
How did you output the color channel for visualization

### ISSUE THREAD

**Issue by Beprominent** [thangvubk/video-super-resolution#3]
Hello, I want to output the color channel for visualization. I input the Y, Cb and Cr channel to the network separately to get their SR image, and then I merged them up to convert them to RGB mode. However, the final picture looks a little strange. So I want to ask you if my method is wrong and how did you get the right RGB mode for visualization? Thanks~

**Comment by Beprominent** [comment]
![1](https://user-images.githubusercontent.com/25165615/55679881-6db98100-5945-11e9-9ada-d05d83741fea.png)
This is the picture I generated.

**Comment by thangvubk** [comment]
Can you expalin why this image is strange?

**Comment by Beprominent** [comment]
This image looks differently from the original image below. It seems like it's not a correct RGB mode image. And I don' t know how to  solve it. 
![Screenshot from 2019-04-08 06-31-19](https://user-images.githubusercontent.com/25165615/55680314-d8b98680-594a-11e9-96f7-c07666e711f4.png)

The visualized images you used for comparison is what I want. And I want to know how did you combine the three channel to get the final result? Could you please show me your code of combination?

![2](https://user-images.githubusercontent.com/25165615/55680431-1834a280-594c-11e9-977a-1e994c66c571.png)

**Comment by Beprominent** [comment]
This image looks different from the original image below. It seems like the image I generated is not a correct RGB mode image. And I don' t know how to solve it.
![Screenshot from 2019-04-08 06-31-19](https://user-images.githubusercontent.com/25165615/55680468-6f3a7780-594c-11e9-8027-aca9993eb47a.png)

The visualized images you used for comparison is what I want. And I want to know how did you combine the three channel to get the final result? Could you please show me your code of combination? Thanks~
![2](https://user-images.githubusercontent.com/25165615/55680472-79f50c80-594c-11e9-9950-fa837b5d20f0.png)

**Comment by thangvubk** [comment]
I think there is some problem with data range it should be in [0, 255] integer, or [0, 1] double. You should keep track of the data range at each step. The image is preprocessed in Matlab so I recommend you to colorize it by Matlab also.

**Comment by Beprominent** [comment]
OK, thanks for your reply.
